### ISSUE TITLE
How to disable wii tilt auto center on dolphin emulator for Android?

### ISSUE THREAD

**Issue by khenlrcn19** [Oblomov/wiimote-pad#10]
Hello, I played Project Zero 2 (Fatal Frame II: Crimson Butterfly Wii edition) with Dolphin emulator mmj on android.

everything worked fine until i have to photograph the thing that is on top of a floor, I can move the camera but it will always go back to the center of the screen,  i need to keep the camera stay still on the bottom or top of the screen.
Is there a way to remove or disable auto center on Emulated Wiimote tilt in dolphin mmj or official build on android?

**Comment by Oblomov** [comment]
I have no idea, this has nothing to do with Wiimote Pad. Please contact the Dolphin team for this kind of issues.
