### ISSUE TITLE
Wiimote as a Light Gun

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Oblomov/wiimote-pad#2]
Do you know of any way that the Wiimote IR Sensor could correspond to an Analogue joypad Axis for use as a Light Gun in Light Gun oriented games?

**Comment by Oblomov** [comment]
This was also discussed in issue #1 —the use of the IR sensor as lightgun is outside the scope of `wiimote-pad`. Use of the IR sensor should be possible via the `xf86-input-wiimote` X.org input module.

**Comment by BadDude** [comment]
I slightly modified Oblomov's code to turn it into "wiimote-lightgun". If you want, I can open a branch.  However, I note that I am not good at coding, so the code could be quite rude. In any case, it serves the purpose.

**Comment by Zombie-Ryushu** [comment]
I would be very appreciative of that, as I'm not trying to use the  WiiMote as an X.org pointer. I'm trying to use it as an Analogue Axis, because there is the strong possibility  I am going to have more than one Wiimote Paired.

**Comment by BadDude** [comment]
I modified the code for the very same reason. For instance I use it to play lightgun games with multiple players (I suggest you to calibrate the wiimote with jstest-gtk). The IR inputs will be recognized both as joystick and mouse axes. You can disable the corresponding xinput to stop moving the mouse with the wiimote.

I tried to pull the commit of the new branch but I do not have the permissions (it is the first time I try to pull a commit so please be patient if I am missing something).

**Comment by Zombie-Ryushu** [comment]
You are Forking, not Pulling. You need to Fork this project into your own Repository. Pulling is when your changes get updated back into the main tree. You need to fork this project and then it will be up to Oblomov to pull your changes should he change his mind.

**Comment by BadDude** [comment]
Ok it is done. Thanks.

**Comment by Zombie-Ryushu** [comment]
Now you need to contribute your changes (called a git push) to the code.

**Comment by BadDude** [comment]
already done... I can see my changes on github.

**Comment by Zombie-Ryushu** [comment]
I'm trying to get an RPM Packaged of this, Is this a module?

**Comment by Zombie-Ryushu** [comment]
I have it compiled and the program runs, but I am not seeing the desired response from the Wiimote. I also have several Patches to commit.

**Comment by BadDude** [comment]
Did you compile form the wiimote-lightgun branch? and do you have an up-to-date version of xwiimote installed?

**Comment by Zombie-Ryushu** [comment]
I did, and I sort of wish I had a more consistent way to work with you, do you use the FreeNode IRC Network? I have complete documentation of everything I have built. As well as all Patches.

**Comment by BadDude** [comment]
I do not have FreeNode and honestly I do not think I will be very useful to help you since coding is not my field. I just modified this code because there was no alternative:)

Which problem do you have? the joystick device is created by the program but it does not have analog axes, yet?

If it can help, I am using wiimote-pad on Ubuntu 15.04, but IR handling worked on previous releases, too (I modified the code more than year ago).

**Comment by Oblomov** [comment]
I'm re-opening this issue because of pull request #3, which however cannot yet be merged as-is currently.

**Comment by Zombie-Ryushu** [comment]
I am using Rosa Linux 2012.1 which uses Kernel 3.10.54. libxwiimote doesn't have an exact version number it just calls itself libxwiimote-2. 

I think the date on the git snapshot is 20131221.
A Build log is here. http://file-store.rosalinux.ru/api/v1/file_stores/ff838e65ca4b940b7fec7b500e015e6ad9812eb9.log?show=true

**Comment by Zombie-Ryushu** [comment]
The unit shows up as having 20 IR Axes and 20 Buttons to jstest. none are responsive and neither is the IR.

**Comment by Oblomov** [comment]
As explained in the README, Wiimote support had huge improvements in kernel 3.11, anything before is unlikely to work well.

**Comment by BadDude** [comment]
20 axes and buttons sounds very weird to me. Do you have the same issue with the original Oblomov's program? Updating xwiimote is indeed the first thing to try.

**Comment by Zombie-Ryushu** [comment]
I can't determine what version of xwiimote I really have. I'm going to try this with a machine running 3.14.44 and see if I get a different results.

**Comment by BadDude** [comment]
I just tried to install it on another laptop (lubuntu 15.04). I just installed xwiimote, libxwiimote-dev, and libu-dev from the common repositories. The code is running nicely also on this laptop. The joystick created has 10 buttons and 2 axes (IR).

**Comment by Zombie-Ryushu** [comment]
I just tried it on my Rosa 2014.1 Laptop. It works, it creates "Lightgun 0" but the geometry is not very accurate and it seems to jump around some. Also its moving the laptop's Mouse Cursor too.

**Comment by BadDude** [comment]
Great! Actually I do have the same issues, but there are easy workarounds:

- concerning the fact that it moves the mouse: as I mentioned in a previous comment, it is sufficient to disable the corresponding xinput (just run in the terminal xinput disable <deviceid>)

- concerning the fact that the cursor jumps (I guess you are not in direct sunlight first of all): I have 3 wiimotes, one is original and two others are form other brands than nintendo. For the original and for one of the two others, it is sufficient tu run wiimote-pad and there is not the jump problem. For the third one, I have to run xwiishow for the corresponding wiimote on another terminal before launching wiimote-pad. Do not close xwiishow while xwiimote-pad is running. I do not know why it happens, but this works for me.

- finally, as I previously mention, once the cursor is no more jumping it will not be calibrated of course. You can calibrate the gun with jstest-gtk, which provides you with a very nice GUI for this purpose (I gust open the calibration window and move the lightgun such that it spans over the range of interest).


I hope this can help.

If you are able to fix these two small bugs directly in wiimote-pad (or xwiimote, I have no idea which is the responsible) it would be of interest to me.

**Comment by Zombie-Ryushu** [comment]
I have it working on the machine still running Rosa 2012.1 (Kernel 3.10.54.)  but even though xwiishow shows correct information, jscal, and jstest show wildly innaccurate Axis readings for the Light gun. As well as wildly innaccurate detection on Mame. Running xwiishow and disabling the accelerometers does not help.

**Comment by Zombie-Ryushu** [comment]
Testing on the Rosa 2014.1 (kernel 3.14.44) Laptop yields the exact same results. There is some terrible logic problem or coordinate calculation issue. xwiishow shows the correct coordinates for the pointers, wiimote-pad does not. You need to have a look at your program.

**Comment by Oblomov** [comment]
If you are talking about wiimote-lightgun, please open an issue about it in [BadDude's repository](https://github.com/BadDude/wiimote-pad/tree/wiimote-lightgun), since this is not a feature of wiimote-pad (at least not currently). (BTW, @BadDude, it seems you have issues disabled on your repository).

If you are experiencing the same issue with wiimote-pad, please open a specific issue for it, thanks.
