### ISSUE TITLE
Patches for various Compile time issues.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Oblomov/wiimote-pad#4]
I have some Patches for one or two Compile time issues.
--- /Makefile   2015-08-06 21:25:08.000000000 -0400
+++ /Makefile   2015-08-06 21:46:30.000000000 -0400
@@ -1,7 +1,7 @@
 XWIIMOTE=../xwiimote/lib
 
 wiimote-pad: wiimote-pad.c
-       $(CC) -Wall -o $@ $< -I$(XWIIMOTE) -ludev -lxwiimote
+       $(CC) -Wall -o $@ $< -I$(XWIIMOTE) -lm -ludev -lxwiimote
 
 clean:
        @rm -rf wiimote-pad
--- /Makefile   2015-08-06 21:46:30.000000000 -0400
+++ /Makefile   2015-08-06 22:36:06.000000000 -0400
@@ -1,7 +1,7 @@
 XWIIMOTE=../xwiimote/lib
 
 wiimote-pad: wiimote-pad.c
-       $(CC) -Wall -o $@ $< -I$(XWIIMOTE) -lm -ludev -lxwiimote
+       $(CC) $(CFLAGS) $(LDFLAGS) -Wall -o $@ $< -I$(XWIIMOTE) -lm -ludev -lxwiimote
 
 clean:
        @rm -rf wiimote-pad

**Comment by Oblomov** [comment]
Is this patch needed by the master branch? I think the addition of -lm is only needed by your lightgun changes, not in `wiimote-pad`. You should commit these changes and push them to your lightgun branch rather than opening new issues about them.
