### ISSUE TITLE
Classic Controller support?

### ISSUE THREAD

**Issue by Rafael8661** [Oblomov/wiimote-pad#6]
I got it work fine with my wiimote, but it's not the better way to play the most of the games... why classic controller isn't supported? (or it is and I don't know how?)
Anyway, thank you for this useful tool. ;)

**Comment by Oblomov** [comment]
I don't personally have a Classic Controller, so I would have absolutely no way to test it. That being said, the purpose of this particular program is specifically to use the Wiimote in “gamepad” mode. For other uses of Wiimote and relate tools, `xwiimote` and related tools are what you should be looking into.
